/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author marth
 */
public class index extends javax.swing.JFrame {

    /**
     * Creates new form index
     */
    public index() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        bg = new javax.swing.JPanel();
        left_panel = new javax.swing.JPanel();
        LPG = new javax.swing.JRadioButton();
        Petrol = new javax.swing.JRadioButton();
        Diesel = new javax.swing.JRadioButton();
        top_right_panel = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        enter_addres = new javax.swing.JLabel();
        Search_for = new javax.swing.JLabel();
        address_var = new javax.swing.JTextField();
        separator = new javax.swing.JSeparator();
        right_panel = new javax.swing.JPanel();
        average_text = new javax.swing.JLabel();
        exit = new javax.swing.JLabel();
        station_text = new javax.swing.JLabel();
        sep1 = new javax.swing.JSeparator();
        sep2 = new javax.swing.JSeparator();
        avg_price_var = new javax.swing.JLabel();
        station_price_var = new javax.swing.JLabel();
        pln2 = new javax.swing.JLabel();
        pln1 = new javax.swing.JLabel();
        logo = new javax.swing.JLabel();
        logout = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        bg.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        left_panel.setBackground(new java.awt.Color(80, 94, 147));

        LPG.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        LPG.setForeground(new java.awt.Color(240, 240, 240));
        LPG.setText("LPG");
        LPG.setOpaque(false);

        Petrol.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        Petrol.setForeground(new java.awt.Color(240, 240, 240));
        Petrol.setText("Diesel");
        Petrol.setOpaque(false);
        Petrol.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PetrolActionPerformed(evt);
            }
        });

        Diesel.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        Diesel.setForeground(new java.awt.Color(240, 240, 240));
        Diesel.setText("Petrol 95");
        Diesel.setOpaque(false);

        top_right_panel.setBackground(new java.awt.Color(64, 68, 121));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/user.png"))); // NOI18N

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(240, 240, 240));
        jLabel2.setText("namexxx");

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(240, 240, 240));
        jLabel4.setText("Logged as:");

        javax.swing.GroupLayout top_right_panelLayout = new javax.swing.GroupLayout(top_right_panel);
        top_right_panel.setLayout(top_right_panelLayout);
        top_right_panelLayout.setHorizontalGroup(
            top_right_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(top_right_panelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        top_right_panelLayout.setVerticalGroup(
            top_right_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, top_right_panelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(top_right_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jLabel4))
                .addGap(23, 23, 23))
            .addGroup(top_right_panelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel3)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        enter_addres.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        enter_addres.setForeground(new java.awt.Color(240, 240, 240));
        enter_addres.setText("Enter your address:");

        Search_for.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        Search_for.setForeground(new java.awt.Color(240, 240, 240));
        Search_for.setText("Search for:");

        address_var.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        address_var.setForeground(new java.awt.Color(240, 240, 240));
        address_var.setText("Miastojakies ul. Wkurwedługanazwa 78/234");
        address_var.setBorder(null);

        javax.swing.GroupLayout left_panelLayout = new javax.swing.GroupLayout(left_panel);
        left_panel.setLayout(left_panelLayout);
        left_panelLayout.setHorizontalGroup(
            left_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(top_right_panel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(left_panelLayout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addGroup(left_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Petrol)
                    .addComponent(Search_for)
                    .addGroup(left_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(enter_addres)
                        .addComponent(address_var, javax.swing.GroupLayout.DEFAULT_SIZE, 235, Short.MAX_VALUE)
                        .addComponent(separator))
                    .addComponent(LPG)
                    .addComponent(Diesel))
                .addContainerGap(29, Short.MAX_VALUE))
        );
        left_panelLayout.setVerticalGroup(
            left_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(left_panelLayout.createSequentialGroup()
                .addComponent(top_right_panel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(35, 35, 35)
                .addComponent(Search_for)
                .addGap(18, 18, 18)
                .addComponent(LPG)
                .addGap(5, 5, 5)
                .addComponent(Diesel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(Petrol)
                .addGap(43, 43, 43)
                .addComponent(enter_addres)
                .addGap(18, 18, 18)
                .addComponent(address_var, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(separator, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(202, Short.MAX_VALUE))
        );

        bg.add(left_panel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 290, 600));

        right_panel.setBackground(new java.awt.Color(86, 86, 86));

        average_text.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        average_text.setForeground(new java.awt.Color(240, 240, 240));
        average_text.setText("Average price in city:");

        exit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/close_blue.png"))); // NOI18N
        exit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                exitMouseClicked(evt);
            }
        });

        station_text.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        station_text.setForeground(new java.awt.Color(240, 240, 240));
        station_text.setText("Price on your station:");

        avg_price_var.setFont(new java.awt.Font("Tahoma", 0, 84)); // NOI18N
        avg_price_var.setForeground(new java.awt.Color(240, 240, 240));
        avg_price_var.setText("5,13");

        station_price_var.setFont(new java.awt.Font("Tahoma", 0, 84)); // NOI18N
        station_price_var.setForeground(new java.awt.Color(240, 240, 240));
        station_price_var.setText("5,13");

        pln2.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        pln2.setForeground(new java.awt.Color(240, 240, 240));
        pln2.setText("PLN");

        pln1.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        pln1.setForeground(new java.awt.Color(240, 240, 240));
        pln1.setText("PLN");

        logo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/paliveo_small.png"))); // NOI18N

        logout.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        logout.setForeground(new java.awt.Color(240, 240, 240));
        logout.setIcon(new javax.swing.ImageIcon(getClass().getResource("/logout_button.png"))); // NOI18N
        logout.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                logoutMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout right_panelLayout = new javax.swing.GroupLayout(right_panel);
        right_panel.setLayout(right_panelLayout);
        right_panelLayout.setHorizontalGroup(
            right_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(right_panelLayout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addGroup(right_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(average_text, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(sep1)
                    .addGroup(right_panelLayout.createSequentialGroup()
                        .addComponent(avg_price_var, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(pln1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGap(112, 112, 112)
                .addGroup(right_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(right_panelLayout.createSequentialGroup()
                        .addComponent(station_price_var, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(pln2, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(right_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(station_text, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(sep2)))
                .addGap(0, 124, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, right_panelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(right_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, right_panelLayout.createSequentialGroup()
                        .addComponent(logout)
                        .addGap(18, 18, 18)
                        .addComponent(exit)
                        .addGap(27, 27, 27))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, right_panelLayout.createSequentialGroup()
                        .addComponent(logo)
                        .addContainerGap())))
        );
        right_panelLayout.setVerticalGroup(
            right_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(right_panelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(right_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(exit)
                    .addComponent(logout))
                .addGap(59, 59, 59)
                .addGroup(right_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(average_text)
                    .addComponent(station_text))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(right_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(sep1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(sep2, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(right_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(right_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(avg_price_var, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(pln1, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(right_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(station_price_var, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(pln2, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 259, Short.MAX_VALUE)
                .addComponent(logo))
        );

        bg.add(right_panel, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 0, 720, 600));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(bg, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(bg, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void PetrolActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PetrolActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_PetrolActionPerformed

    private void logoutMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_logoutMouseClicked
        // TODO add your handling code here:
        new login().setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_logoutMouseClicked

    private void exitMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_exitMouseClicked
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_exitMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(index.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(index.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(index.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(index.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new index().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JRadioButton Diesel;
    private javax.swing.JRadioButton LPG;
    private javax.swing.JRadioButton Petrol;
    private javax.swing.JLabel Search_for;
    private javax.swing.JTextField address_var;
    private javax.swing.JLabel average_text;
    private javax.swing.JLabel avg_price_var;
    private javax.swing.JPanel bg;
    private javax.swing.JLabel enter_addres;
    private javax.swing.JLabel exit;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel left_panel;
    private javax.swing.JLabel logo;
    private javax.swing.JLabel logout;
    private javax.swing.JLabel pln1;
    private javax.swing.JLabel pln2;
    private javax.swing.JPanel right_panel;
    private javax.swing.JSeparator sep1;
    private javax.swing.JSeparator sep2;
    private javax.swing.JSeparator separator;
    private javax.swing.JLabel station_price_var;
    private javax.swing.JLabel station_text;
    private javax.swing.JPanel top_right_panel;
    // End of variables declaration//GEN-END:variables
}
