/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author marth
 */
public class register extends javax.swing.JFrame {

    /**
     * Creates new form login
     */
    public register() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        background = new javax.swing.JPanel();
        rightpanel = new javax.swing.JPanel();
        jSeparator1 = new javax.swing.JSeparator();
        email_data = new javax.swing.JTextField();
        username_data = new javax.swing.JTextField();
        jPasswordField1 = new javax.swing.JPasswordField();
        jSeparator2 = new javax.swing.JSeparator();
        jSeparator3 = new javax.swing.JSeparator();
        close_window = new javax.swing.JLabel();
        password = new javax.swing.JLabel();
        username = new javax.swing.JLabel();
        username1 = new javax.swing.JLabel();
        register_button = new javax.swing.JLabel();
        layout = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setLocationByPlatform(true);
        setUndecorated(true);

        background.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        rightpanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        rightpanel.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 282, 390, 10));

        email_data.setBackground(new java.awt.Color(138, 138, 138));
        email_data.setFont(new java.awt.Font("Tahoma", 2, 18)); // NOI18N
        email_data.setForeground(new java.awt.Color(255, 255, 255));
        email_data.setText("Enter e-mail");
        email_data.setBorder(null);
        email_data.setOpaque(false);
        email_data.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                email_dataActionPerformed(evt);
            }
        });
        rightpanel.add(email_data, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 340, 300, 40));

        username_data.setBackground(new java.awt.Color(138, 138, 138));
        username_data.setFont(new java.awt.Font("Tahoma", 2, 18)); // NOI18N
        username_data.setForeground(new java.awt.Color(255, 255, 255));
        username_data.setText("Enter Username");
        username_data.setBorder(null);
        username_data.setOpaque(false);
        username_data.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                username_dataActionPerformed(evt);
            }
        });
        rightpanel.add(username_data, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 240, 300, 40));

        jPasswordField1.setForeground(new java.awt.Color(240, 240, 240));
        jPasswordField1.setText("Enter Password");
        jPasswordField1.setBorder(null);
        jPasswordField1.setCaretColor(new java.awt.Color(240, 240, 240));
        jPasswordField1.setOpaque(false);
        rightpanel.add(jPasswordField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 440, 340, 40));
        rightpanel.add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 480, 390, 10));
        rightpanel.add(jSeparator3, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 382, 380, 10));

        close_window.setIcon(new javax.swing.ImageIcon(getClass().getResource("/close.png"))); // NOI18N
        close_window.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                close_windowMouseClicked(evt);
            }
        });
        rightpanel.add(close_window, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 10, -1, -1));

        password.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        password.setForeground(new java.awt.Color(240, 240, 240));
        password.setText("Password:");
        rightpanel.add(password, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 410, -1, -1));

        username.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        username.setForeground(new java.awt.Color(240, 240, 240));
        username.setText("e-mail:");
        rightpanel.add(username, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 300, -1, -1));

        username1.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        username1.setForeground(new java.awt.Color(240, 240, 240));
        username1.setText("Username:");
        rightpanel.add(username1, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 200, -1, -1));

        register_button.setIcon(new javax.swing.ImageIcon(getClass().getResource("/register_button.png"))); // NOI18N
        rightpanel.add(register_button, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 490, -1, -1));

        layout.setIcon(new javax.swing.ImageIcon(getClass().getResource("/station.png"))); // NOI18N
        rightpanel.add(layout, new org.netbeans.lib.awtextra.AbsoluteConstraints(-10, 0, -1, -1));

        background.add(rightpanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 800, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(background, javax.swing.GroupLayout.PREFERRED_SIZE, 790, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(background, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void email_dataActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_email_dataActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_email_dataActionPerformed

    private void username_dataActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_username_dataActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_username_dataActionPerformed

    private void close_windowMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_close_windowMouseClicked
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_close_windowMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new login().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel background;
    private javax.swing.JLabel close_window;
    private javax.swing.JTextField email_data;
    private javax.swing.JPasswordField jPasswordField1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JLabel layout;
    private javax.swing.JLabel password;
    private javax.swing.JLabel register_button;
    private javax.swing.JPanel rightpanel;
    private javax.swing.JLabel username;
    private javax.swing.JLabel username1;
    private javax.swing.JTextField username_data;
    // End of variables declaration//GEN-END:variables
}
